apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.fullname" . }}-full-service
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: full-service
spec:
  replicas: {{ .Values.fullService.replicaCount }}
  selector:
    matchLabels:
      app: full-service
      {{- include "chart.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "chart.fullname" . }}-full-service
  template:
    metadata:
      annotations:
        {{- toYaml .Values.fullService.podAnnotations | nindent 8 }}
      labels:
        app: full-service
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: full-service
        securityContext:
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
        {{- if eq .Values.fullService.environment "mainnet" }}
        image: "{{ .Values.fullService.image.repository }}:{{ .Values.fullService.image.tag }}-mainnet"
        {{- else }}
        image: "{{ .Values.fullService.image.repository }}:{{ .Values.fullService.image.tag }}-testnet"
        {{- end }}
        imagePullPolicy: {{ .Values.fullService.image.pullPolicy }}
        # Command is needed to override the entrypoint, to remove the wallet-db arg reference
        command:
          - /bin/bash
          - -c
        args: 
          - |
            unset MC_WALLET_DB && /usr/local/bin/full-service \
              --ledger-db=/data/ledger.db \
              --watcher-db=/data/watcher \
              --listen-host=0.0.0.0 \
              --allowed-origin='*' \
              --fog-ingest-enclave-css=/usr/local/bin/ingest-enclave.css \
              {{- if eq .Values.fullService.environment "mainnet" }}
              --peer=mc://node1.prod.mobilecoinww.com/ \
              --tx-source-url=https://ledger.mobilecoinww.com/node1.prod.mobilecoinww.com/ \
              --peer=mc://node2.prod.mobilecoinww.com/ \
              --tx-source-url=https://ledger.mobilecoinww.com/node2.prod.mobilecoinww.com/ \
              --peer=mc://node3.prod.mobilecoinww.com/ \
              --tx-source-url=https://ledger.mobilecoinww.com/node3.prod.mobilecoinww.com/ \
              --peer mc://node1.consensus.mob.production.namda.net:443/ \
              --tx-source-url https://s3-eu-central-1.amazonaws.com/production-namda-payments-ledger/node1.consensus.mob.production.namda.net/ \
              --peer mc://node2.consensus.mob.production.namda.net:443/ \
              --tx-source-url https://s3-eu-central-1.amazonaws.com/production-namda-payments-ledger/node2.consensus.mob.production.namda.net/ \
              --peer mc://blockdaemon.mobilecoin.bdnodes.net:443/ \
              --tx-source-url https://bd-mobilecoin-ledger.s3.amazonaws.com/blockdaemon.mobilecoin.bdnodes.net/ \
              --peer mc://binance.mobilecoin.bdnodes.net:443/ \
              --tx-source-url https://bd-mobilecoin-ledger.s3.amazonaws.com/binance.mobilecoin.bdnodes.net/ \
              --peer mc://ideasbeyondborders.mobilecoin.bdnodes.net:443/ \
              --tx-source-url https://bd-mobilecoin-ledger.s3.amazonaws.com/ideasbeyondborders.mobilecoin.bdnodes.net/ \
              --peer mc://thelongnowfoundation.mobilecoin.bdnodes.net:443/ \
              --tx-source-url https://bd-mobilecoin-ledger.s3.amazonaws.com/thelongnowfoundation.mobilecoin.bdnodes.net/ \
              --peer mc://ams1-mc-node1.dreamhost.com:3223/ \
              --tx-source-url https://s3-eu-west-1.amazonaws.com/dh-mobilecoin-eu/ams1-mc-node1.dreamhost.com/ \
              --chain-id=main
              {{- else }}
              --peer=mc://node1.test.mobilecoin.com/ \
              --peer=mc://node2.test.mobilecoin.com/ \
              --tx-source-url=https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node1.test.mobilecoin.com/ \
              --tx-source-url=https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node2.test.mobilecoin.com/ \
              --chain-id=test
              {{- end }}
        ports:
        - name: full-service
          containerPort: {{ .Values.fullService.listenPort }}
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          {{- toYaml .Values.fullService.resources | nindent 10 }}
      nodeSelector:
        {{- toYaml .Values.fullService.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.fullService.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.fullService.tolerations | nindent 8 }}
      {{- if eq .Values.fullService.persistence.enabled false }}
      volumes:
      - name: data
        emptyDir: {}
      {{- else }}
      volumes: []
      {{- end }}
  {{- if .Values.fullService.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      {{- toYaml .Values.fullService.persistence.spec | nindent 6 }}
  {{- end }}
