nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: docker-credentials

# FullService
fullService:
  # environment = MobileCoin network.
  # Valid values are 'mainnet' or 'testnet'
  environment: "testnet"
  image:
    repository: mobilecoin/full-service
    # tag gets a suffix of "mainnet" or "testnet" based on fullService.environment
    tag: "2.3.0-pre.1"
    pullPolicy: Always
  replicaCount: 1
  listenPort: 9090 # Full-Service default
  podAnnotations:
    fluentbit.io/include: 'true'
  args: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistence:
    enabled: true
    spec:
      storageClassName: fast
      accessModes:
      - 'ReadWriteOnce'
      resources:
        requests:
          storage: 128Gi
  ingress:
    enabled: true
    hostname: readonly-fs-testnet.mobilecoin.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production-http
      haproxy.org/server-ssl: "false" # The backend (server) is http
      haproxy.org/timeout-client: 239s # 4 min timeout on azure
      haproxy.org/timeout-server: 239s
      haproxy.org/timeout-http-keep-alive: 120s
      haproxy.org/backend-config-snippet: |-
        http-reuse aggressive
      haproxy.org/abortonclose: "true"

