name: Build rustdocs

# Run on main and PRs
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  # Build and publish rustdocs
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch rust tooling
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Configure caching
        uses: actions/cache@v2
        with:
          key: docs
          path: |
            ${{ env.HOME }}/.cargo
            ./target

      - name: Build documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          # Manually include packages to avoid SGX related build issues
          # TODO: perhaps replace with `--workspace` and choose feature flags?
          args: |
            --no-deps 
            --package mc-common 
            --package mc-crypto-keys
            --package mc-transaction-core

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        if: github.ref_name == 'develop'
        with:
          target_branch: gh-pages
          build_dir: target/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
